services:
  db:
    image: postgres
    container_name: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $PGPASS
      PGDATA: /var/lib/postgresql/data
    restart: always

  tg_bot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
    links:
      - "db:database"
    volumes:
    - .:/src


